services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - config/.env
    environment:
      - DB_PATH=/app/data/bot.sqlite
      - STORAGE_PATH=/app/storage
    volumes:
      - storage_data:/app/storage
      - bot_data:/app/data
    restart: unless-stopped

volumes:
  bot_data:
  storage_data:
